### ISSUE TITLE
Validation object for Picker having Item Source

### ISSUE THREAD

**Issue by viveklpu2011** [luismts/ValidationRulesPlugin#10]
I want to set the validation object for the picker having item source

**Comment by luismts** [comment]
I dont get it. Can you show me what you are trying to do?

**Comment by luismts** [comment]
Is it [this thread](https://github.com/luismts/ValidationRulesPlugin/issues/11) related?

**Comment by luismts** [comment]
Any news on this @viveklpu2011 ?

**Comment by luismts** [comment]
Related #11
