### ISSUE TITLE
Validation rule for selected item of Picker

### ISSUE THREAD

**Issue by viveklpu2011** [luismts/ValidationRulesPlugin#11]
Want to perform validation of picker that value is selected or not from view model using validation object

**Comment by luismts** [comment]
You can do it by creating your ValidationRule that perform that validation and bind your property to SelectedIten in the picker...

**Comment by viveklpu2011** [comment]
I am trying by passing the model in place of string in validation object but i am not getting selected value of picker. And my requirement is that when i select the value from picker i should get selected value on selection of picker

**Comment by luismts** [comment]
Can you show a snippet?

**Comment by viveklpu2011** [comment]
Let me make clear understanding of my requirement. 

I have a item source of model from view model for picker and i simply want that some value is selected or not from picker and if selected it should show on selected event of picker

**Comment by luismts** [comment]
I dont get it, sorry.

**Comment by luismts** [comment]
Any news on this @viveklpu2011 ?

**Comment by luismts** [comment]
The new version has support for Lists that you can use with your pickers. Check it out [here](https://github.com/luismts/ValidationRulesPlugin/releases/tag/v1.4.0)
