### ISSUE TITLE
Value not updating

### ISSUE THREAD

**Issue by d-dev-101** [luismts/ValidationRulesPlugin#16]
## Bug Information

Version Number of Plugin: 1.3.1
Device Tested On: Pixel 2 Pie 9.0 - API 28
Simulator Tested On: Android Device Manager
Version of VS: 16.10.3
Version of Xamarin: 16.10.000.234
Versions of other things you are using:

### Steps to reproduce the Behavior

I have a simple form with 3 numeric entries, on unfocus I validate the entry. If I focus on the entry, enter a value then delete the entered value before unfocusing, when I check the value of within Validatable<T> the first number in the value I entered before unfocusing is the value. For example if I enter 100 as the value and delete it before unfocusing the value will be 1. I haven't put Mode=TwoWay on 2 of the fields as regardless this is an issue for me. 

Apologies in advance I am new to xamarin so my knowledge is limited

### Screenshots

**Form:**

![image](https://user-images.githubusercontent.com/33750091/125950679-ae9f5ca2-98ac-42ab-96b5-7783a131b3ec.png)

**Unfocused Events:**

![image](https://user-images.githubusercontent.com/33750091/125950818-27f057f2-2bee-45dd-b5e6-d048f7083981.png)

**Viewmodel:**

![image](https://user-images.githubusercontent.com/33750091/125951030-86c4d72e-6984-4612-a82e-b4cb77ed6cab.png)

**Comment by luismts** [comment]
So, did you fixed or not?

**Comment by d-dev-101** [comment]
No, is it an issue you're able to reproduce yourself? I've tried a normal nullable int property and checked to see if the same issue exists but it's fine. Do you think it's an issue with the binding of the Validatable.Value?

**Comment by d-dev-101** [comment]
I've managed to fix this issue by getting the value from the sender within the Unfocused event that is triggered and change the value to null:

![image](https://user-images.githubusercontent.com/33750091/125966259-14962bec-68ec-476c-ad71-b06f5724ecb8.png)

I would still try to reproduce this on your end to see if this is an issue with the binding of the value when you get time but thanks for your response.
