### ISSUE TITLE
Converter not hitting on command

### ISSUE THREAD

**Issue by viveklpu2011** [luismts/ValidationRulesPlugin#7]
Coverters is not hitting when perform command event so err msg not showing in label and placeholder entry.

I am using mvvm helper as a base view model

**Comment by luismts** [comment]
I think you are talking about `ValueFormatter` right?

`ValidateCommand` triggers the validation process with the value you already have. If you want to format the value, you need to change the value in order to trigger the `ValueFormatter`.

**Comment by luismts** [comment]
Or you are talking about Binding Converters?

**Comment by viveklpu2011** [comment]
InverseBoolConverter is not hitting on command, but it should hit when there is any validation error 

This is my code below in which placeholder color as well as label is not visible when entry is null



<StackLayout Orientation="Horizontal">
                        <Entry
                            BackgroundColor="Transparent"
                            HorizontalOptions="FillAndExpand"
                            Placeholder="Customer/Party Name*"
                            PlaceholderColor="Gray"
                            Text="{Binding CustomerName.Value, Mode=TwoWay}"
                            TextColor="Black">
                            <Entry.Behaviors>
                                <behaviour:EntryLineValidationBehaviour IsValid="{Binding CustomerName.IsValid}" />
                            </Entry.Behaviors>
                        </Entry>
                        <ImageButton
                            x:Name="btnContacts"
                            BackgroundColor="Transparent"
                            Clicked="btnContacts_Clicked"
                            HeightRequest="40"
                            HorizontalOptions="End"
                            VerticalOptions="CenterAndExpand"
                            WidthRequest="40">
                            <ImageButton.Source>
                                <FontImageSource
                                    FontFamily="UserIcons"
                                    Glyph="{x:Static fonticon:FontIconsClass.AccountBox}"
                                    Size="30"
                                    Color="Black" />

                            </ImageButton.Source>
                        </ImageButton>
                    </StackLayout>

                    <Label
                        IsVisible="{Binding CustomerName.IsValid, Converter={StaticResource InverseBoolConverter}}"
                        Style="{StaticResource ErrorTextStyle}"/>

**Comment by luismts** [comment]
This is related to your implementation. Nothing to do here.
