### ISSUE TITLE
Entry Value not cleared

### ISSUE THREAD

**Issue by viveklpu2011** [luismts/ValidationRulesPlugin#8]
Not able to clear all the entry value, after setting the valdition object to null. Value still showing in entry

**Comment by luismts** [comment]
Can you show me a snippet?

**Comment by viveklpu2011** [comment]
CustomerAddress.Value = CustomerName.Value = CustomerPhone.Value = CustomerShopName.Value = string.Empty;

**Comment by luismts** [comment]
I will test

**Comment by luismts** [comment]
I found the issue and I fixed it. It Will be released later

**Comment by luismts** [comment]
Fixed https://github.com/luismts/ValidationRulesPlugin/pull/12
