### ISSUE TITLE
Not able to set the entry value from View model

### ISSUE THREAD

**Issue by viveklpu2011** [luismts/ValidationRulesPlugin#9]
Not able to set the entry value programatically , meanse i want to fill entry from view model from validation object

**Comment by luismts** [comment]
I never tried but I think you can do it. The `validatable `object already implements `PropertyChange`.

**Comment by viveklpu2011** [comment]
I have tried but not working

**Comment by luismts** [comment]
Can you show a snippet?

**Comment by viveklpu2011** [comment]
var contact = await Contacts.PickContactAsync();

                if (contact == null)
                    return;

                customerViewModel.CustomerName.Value = contact?.DisplayName;
                customerViewModel.CustomerPhone.Value = contact?.Phones[0]?.PhoneNumber;




Value is not showing in entry

**Comment by luismts** [comment]
Sorry, I can't reproduce this. It's working on my side. 

You can see an example [here](https://github.com/luismts/ValidationRulesPlugin/blob/a4c3421cb4231683d27e2fa994ad41b927211572/samples/ValidationRulesTest/ValidationRulesTest/ViewModels/Example4ViewModel.cs#L31).
